Update README.md
Davidmd00/iv-DMD pull request #3
Opened 2022-09-22 14:36 UTC by Davidmd00

2022-09-24 08:50 UTC, JJ commented
Por favor, seguid la lista de comprobación.

2022-09-24 08:50 UTC, JJ requested changes
Por favor, lee el guión del objetivo para ver qué problemas son aceptables, y las condiciones que tiene que cumplir la solución.

2022-09-30 17:26 UTC, Davidmd00 commented
@JJ Revisión de una nueva idea.

2022-09-30 17:54 UTC, JJ requested changes
Cuanto antes entendáis que esto no es un "ejercicio" donde casi cualquier cosa vale, mejor. Tenéis que describir un problema real, que vais a ir resolviendo de la mejor manera posible a lo largo de la asignatura. Por favor, repasa lo que se busca en este objetivo en el guión del mismo y pregunta lo que no entiendas.

2022-09-30 17:54 UTC, JJ commented on README.md
> +# App para gestionar las peñas deportivas
No se os pide que describáis un app, sino una idea.
Aparte, no has usado nunca la clave pública, como pone en la captura. Aunque es aceptable que uséis la web, conviene que empecéis a usar git desde la línea de órdenes, no podéis estar siempre así.

2022-09-30 17:54 UTC, JJ commented on README.md
> +  Con esta app se creará un perfil de cada jugador de la peña, apuntando después de cada partido cuantos goles ha metido, cuantas paradas ha realizado, si ha ganado o ha perdido, etc. En el siguiente
No intentéis convertir en un problema lo que no es, ni dar soluciones que no lo son. Un jugador no se describe por los goles que ha metido, ni es realmente un problema formar equipos. No conozco ni un solo encuentro de gente que se haya deshecho porque no podían formar equipos. Por favor, tratad de buscar problemas reales que se puedan resolver con un programa.

2022-09-30 17:54 UTC, JJ commented on README.md
> +  La aplicación simulará el partido con los equipos al azar, y con una heurística se irán generando equipos y cambiando los jugadores hasta que los equipos se encuentren lo más equilibrados posible,
Ahora sí que estoy sorprendido. ¿Vas a escribir un simulador de partidos de fútbol para el objetivo 4 de la asignatura?

2022-10-01 16:55 UTC, Davidmd00 commented
@JJ Revisión de una nueva idea.

2022-10-01 16:59 UTC, JJ requested changes
Repasa las preguntas frecuentes del guión del objetivo cero, por favor.

2022-10-01 16:59 UTC, JJ commented on README.md
> +  En muchas ocasiones cuando vamos a un restaurante nos encontramos con el dilema de no saber qué plato pedir al no saber qué ingredientes lleva (principalmente la gente vegetariana o alérgica a algú
¿Vas a meter tú los platos del restaurante de todos los restaurantes donde vayas a ir? Si no lo piensas hacer, esto ni es un problema ni puedes resolverlo en la asignatura.
Como indica el guión, problemas que requieran entrada masiva de datos por parte del usuario no son aceptables, simplemente porque el usuario no los va a usar.

2022-10-01 16:59 UTC, JJ commented on README.md
> +  Esta carta interactiva mostrará fotos de todos los platos que se encuentren en la carta del restaurante, así como sus ingredientes y toda la información acerca de estos. Además, aparecerá un tiempo
De veras, repasa el guión del objetivo cero para ver el tipo de problemas que se van a poder desarrollar en la asignatura y por qué se restringe los problemas a esos.

2022-10-03 11:14 UTC, Davidmd00 commented on README.md
> +  En muchas ocasiones cuando vamos a un restaurante nos encontramos con el dilema de no saber qué plato pedir al no saber qué ingredientes lleva (principalmente la gente vegetariana o alérgica a algú
@JJ ¿Y si lo simplifico a solo tener las fotos de cada plato (sin ingredientes ni calorías) en la carta, junto con el tiempo aproximado de preparación (lógica de negocio) y el número de platos preparados ese dia? Trabajar con 20 fotos por restaurante no creo que sea una cantidad de datos masiva.

2022-10-03 11:17 UTC, JJ commented on README.md
> +  En muchas ocasiones cuando vamos a un restaurante nos encontramos con el dilema de no saber qué plato pedir al no saber qué ingredientes lleva (principalmente la gente vegetariana o alérgica a algú
¿Y si buscas otro problema donde *sí* tengas datos y el usuario no tenga que introducir nada?
¿Has mirado también la lógica de negocio que necesitarías para procesar fotos?
Por favor, mira un elemento de la lista de comprobación que he añadido hoy y el nuevo problema que plantees sería conveniente que lo tuviera en cuenta.

2022-10-04 14:44 UTC, Davidmd00 commented
@JJ Revisión de una nueva idea.

2022-10-07 06:57 UTC, Davidmd00 commented
@JJ Update Readme

2022-10-07 07:52 UTC, JJ approved these changes
👍

2022-10-12 08:16 UTC, merged

2022-10-16 07:44 UTC, JJ commented
Deberías intentar entregar lo antes posible el objetivo 1. Por favor, no lo retrases, que ya va muy avanzado el curso.